config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check



  # Defines the root path route ("/")
  # root "posts#index"
  root "trello#index"

  resources :trello
  resources :work_teams do
    resources :boards
    member do
      get 'add_users'
      patch 'update_users'
    end
  end
  resources :boards do
    #member do
   #   patch 'move'
    #end
    resources :tasks do 
      member do
        patch 'move'
      end
    end
  end
  resources :users
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :work_team
  belongs_to :design, optional: true

  has_many :tasks
  validates :name, :description, presence: true

  

end

app/models/design.rb
class Design < ActiveRecord::Base
    has_many :boards
    validates :name, :type_of_attribute, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :board # relación uno a muchos con Board

  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id', optional: false
  belongs_to :assignee, class_name: 'User', foreign_key: 'assignee_id', optional: false

  validates :title, :description, :status, :priority, presence: true

  enum status: { 'TO DO': 0, 'WIP': 1, 'DONE': 2 }
  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :work_users
  has_many :work_teams, through: :work_users
  has_many :boards, through: :work_users, source: :work_team

  has_many :created_tasks, class_name: 'Task', foreign_key: 'creator_id'
  has_many :assigned_tasks, class_name: 'Task', foreign_key: 'assignee_id'

  validates :first_name, :last_name, :position, :email, :password, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "debe ser un correo electrónico válido" }
  validates :password, length: { minimum: 6, message: "debe tener al menos 6 caracteres" }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/work_team.rb
class WorkTeam < ActiveRecord::Base
    has_many :work_users
    has_many :users, through: :work_users
  
    has_many :boards
  
    validates :name, presence: true

    accepts_nested_attributes_for :users
  end

app/models/work_user.rb
class WorkUser < ActiveRecord::Base
    belongs_to :user
    belongs_to :work_team
  
    validates :user_id, :work_team_id, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

    def show
      @board = Board.find(params[:id])
      @tasks = @board.tasks
    end
  
    def new
      @team = WorkTeam.find(params[:work_team_id])
      @board = @team.boards.build
    end
  
    def create
      @team = WorkTeam.find(params[:work_team_id])
      @board = @team.boards.build(board_params)
      
      if @board.save
        redirect_to @team, notice: 'Board was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def board_params
      params.require(:board).permit(:name, :description)
    end
  
  end
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def show
      @task = Task.find(params[:id])
    end
  
    def new
      @board = Board.find(params[:board_id])
      @task = @board.tasks.build
      @users = @board.work_team.users
    end
  
    def create
      @board = Board.find(params[:board_id])
      @task = @board.tasks.build(task_params)
      
      if @task.save
        redirect_to @board, notice: 'Task was successfully created.'
      else
        @users = @board.work_team.users  # Asegúrate de cargar los usuarios nuevamente en caso de error
        render :new
      end
    end

    def move
      @task = Task.find(params[:id])
      if @task.update(status: params[:status])
        redirect_to @task, notice: 'Task status was successfully updated.'
      else
        redirect_to @task, alert: 'Failed to update task status.'
      end
    end

    def destroy
      @task = Task.find(params[:id])
      board = @task.board  # Guarda la referencia del tablero antes de destruir la tarea
      @task.destroy
    
      respond_to do |format|
        format.html { redirect_to board_path(board), notice: "Task was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
  
    def task_params
      params.require(:task).permit(:title, :description, :status, :priority, :creator_id, :assignee_id)
    end
  end
  

app/controllers/trello_controller.rb
class TrelloController < ApplicationController
    def index
        @teams = WorkTeam.all
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @work_teams = @user.work_teams
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            redirect_to users_path, notice: 'Task was successfully created.'
        else
            render :new
        end
    end

    private
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :position, :email, :password)
    end
end

app/controllers/work_teams_controller.rb
class WorkTeamsController < ApplicationController

    def index 
        @teams = WorkTeam.all
    end

    def show
        @team = WorkTeam.find(params[:id])
        @boards = @team.boards 
        @users = @team.users
	end

    def new
        @work_team = WorkTeam.new
    end

    def create
        @work_team = WorkTeam.new(work_team_params)
        if @work_team.save
            add_users_to_work_team
            redirect_to @work_team, notice: 'Work team was successfully created.'
        else
            render :new
        end
    end

    def add_users
        @work_team = WorkTeam.find(params[:id])
    end
    
    def update_users
        @work_team = WorkTeam.find(params[:id])
        add_users_to_work_team
        redirect_to @work_team, notice: 'Users were successfully added to the team.'
    end

    private

    def work_team_params
        params.require(:work_team).permit(:name, :description, user_emails: [])
    end

    def add_users_to_work_team
        emails = params[:work_team][:user_emails].split(',').map(&:strip).reject(&:blank?)
        emails.each do |email|
          user = User.find_by(email: email)
          @work_team.users << user if user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/new.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h1 class="text-center">New Board</h1>
    </div>
    <div class="card-body">
      <%= form_with(model: [@team, @board], local: true) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", required: true %>
        </div>

        <div class="actions text-center">
          <%= form.submit 'Save', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center mt-3">
    <%= link_to 'Back', work_team_path(@team), class: 'btn btn-secondary' %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Info del Board: <%= @board.name %></h1>

  <div class="row">
    <% ['TO DO', 'WIP', 'DONE'].each do |status| %>
      <div class="col-md-4">
        <h3><%= status %></h3>
        <ul class="list-group">
          <% @tasks.select { |task| task.status == status }.each do |task| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= task.title %>
              <%= link_to 'View', task_path(task), class: 'btn btn-primary btn-sm' %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= link_to 'New Task', new_board_task_path(@board), class: 'btn btn-success mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/trello">Trello</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/trello">Home</a>
            <li class="nav-item dropdown">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/users">Users</a>
            <li class="nav-item dropdown">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/work_teams">Teams</a>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [@board, task], local: true) do |form| %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys, {}, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :priority %>
    <%= form.number_field :priority, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :creator_id, "Creator" %>
    <%= form.collection_select :creator_id, @board.work_team.users, :id, :full_name, {prompt: "Select a creator"}, {class: "form-control"} %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :assignee_id, "Assignee" %>
    <%= form.collection_select :assignee_id, @board.work_team.users, :id, :full_name, {prompt: "Select an assignee"}, {class: "form-control"} %>
  </div>

  <%= form.hidden_field :board_id, value: @board.id %>

  <div class="actions">
    <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Aqui se crea un task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="container mt-4">
  <h1 class="text-center">Detalles de la Tarea</h1>
  <div class="card mt-4">
    <div class="card-body">
      <h2><%= @task.title %></h2>
      <p><strong>Descripción:</strong> <%= @task.description %></p>
      <p><strong>Estado:</strong> <%= @task.status %></p>
      <p><strong>Prioridad:</strong> <%= @task.priority %></p>
      <p><strong>Creador:</strong> <%= @task.creator.first_name %> <%= @task.creator.last_name %></p>
      <p><strong>Responsable:</strong> <%= @task.assignee.first_name %> <%= @task.assignee.last_name %></p>
      <p><strong>Tablero:</strong> <%= link_to @task.board.name, board_path(@task.board) %></p>
      <p><strong>Creado:</strong> <%= @task.created_at.strftime("%d de %B, %Y %H:%M") %></p>
      <p><strong>Actualizado:</strong> <%= @task.updated_at.strftime("%d de %B, %Y %H:%M") %></p>
      
      <% ['TO DO', 'WIP', 'DONE'].each do |status| %>
        <% unless @task.status == status %>
          <%= form_with url: move_board_task_path(@task.board, @task, status: status), method: :patch, class: 'd-inline' do |form| %>
            <%= form.submit "Mover a #{status}", class: "btn btn-outline-primary" %>
          <% end %> <!-- Closing form_with -->
        <% end %> <!-- Closing unless -->
      <% end %> <!-- Closing each -->
    </div>
  </div>
</div>

app/views/trello/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Bienvenido a Trello</h1>
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <div class="mb-3">
        <%= link_to 'Ver Todos los Teams', work_teams_path, class: 'btn btn-lg btn-primary' %>
      </div>
      <div class="mb-3">
        <%= link_to 'Ver Todos los Users', users_path, class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/user/show.html.erb
<!-- app/views/users/show.html.erb -->
<h1>User Details</h1>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @user.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @user.created_at.strftime("%B %d, %Y %H:%M") %>
</p>

<p>
  <strong>Updated At:</strong>
  <%= @user.updated_at.strftime("%B %d, %Y %H:%M") %>
</p>

<h2>Work Teams:</h2>
<% if @work_teams.present? %>
  <ul>
    <% @work_teams.each do |work_team| %>
      <li><%= work_team.name %> - <%= work_team.description %></li>
    <% end %>
  </ul>
<% else %>
  <p>No work teams found.</p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="form-group mb-3">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :position %>
        <%= form.text_field :position, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", required: true %>
      </div>

      <div class="actions">
        <%= form.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Todos los Usuarios</h1>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Position</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= "#{user.first_name} #{user.last_name}" %></td>
            <td><%= user.email %></td>
            <td><%= user.position %></td>
            <td>
              <%= link_to 'Show', user_path(user), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-secondary btn-sm' %>
              <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'New User', new_user_path, class: 'btn btn-success btn-sm' %>
</div>

app/views/users/new.html.erb
<div class="container mt-4">
  <h1 class="text-center">New User</h1>
  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h1>Detalles del Usuario</h1>
    </div>
    <div class="card-body">
      <p><strong>Nombre:</strong> <%= @user.first_name %> <%= @user.last_name %></p>
      <p><strong>Cargo:</strong> <%= @user.position %></p>
      <p><strong>Email:</strong> <%= @user.email %></p>
      <p><strong>Fecha de creación:</strong> <%= @user.created_at.strftime("%d de %B, %Y %H:%M") %></p>
      <p><strong>Última actualización:</strong> <%= @user.updated_at.strftime("%d de %B, %Y %H:%M") %></p>
    </div>
  </div>

  <div class="mt-4">
    <h2>Equipos de Trabajo</h2>
    <% if @work_teams.present? %>
      <ul class="list-group">
        <% @work_teams.each do |work_team| %>
          <li class="list-group-item">
            <%= work_team.name %> - <%= work_team.description %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-muted">No se encontraron equipos de trabajo.</p>
    <% end %>
  </div>
</div>

app/views/work_team/show.html.erb
<h1>Aqui se ve la info de un team</h1>

<h1><%= @team.name %></h1>

<h2>Boards:</h2>
<ul>
  <% @boards.each do |board| %>
    <li><%= board.name %></li> <!-- Asumiendo que cada board tiene un atributo 'name' -->
    <%= link_to 'View', board, class: 'card-link btn btn-primary' %>
  <% end %>
</ul> 

<h1>Aqui se muetran todos los user del work team</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %></li> <!-- Asumiendo que cada board tiene un atributo 'name' -->
    <%= link_to 'View', user, class: 'card-link btn btn-primary' %>
  <% end %>
</ul>

app/views/work_teams/add_users.html.erb
<div class="container mt-4">
  <h1 class="text-center">Add Users to <%= @work_team.name %></h1>

  <div class="card">
    <div class="card-body">
      <%= form_with(model: @work_team, url: update_users_work_team_path(@work_team), method: :patch, local: true) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :user_emails, "Enter user emails separated by commas" %>
          <%= form.text_area :user_emails, class: "form-control", rows: 3, placeholder: "e.g., user1@example.com, user2@example.com" %>
        </div>

        <div class="actions">
          <%= form.submit 'Add Users', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Back to Team', work_team_path(@work_team), class: 'btn btn-secondary mt-3' %>
</div>

app/views/work_teams/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Aqui se muestran todos los work teams</h1>
  
  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @teams.each do |work_team| %>
          <tr>
            <td><%= work_team.name %></td>
            <td><%= work_team.description %></td>
            <td>
              <%= link_to 'Show', work_team_path(work_team), class: 'btn btn-primary' %>
              <%= link_to 'Edit', edit_work_team_path(work_team), class: 'btn btn-secondary' %>
              <%= link_to 'Delete', work_team_path(work_team), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New', new_work_team_path, class: 'btn btn-success btn-sm' %>
  </div>

app/views/work_teams/new.html.erb
<div class="container mt-4">
  <h1 class="text-center">Create New Work Team</h1>

  <div class="card">
    <div class="card-body">
      <%= form_with(model: @work_team, local: true) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :name, 'Team Name' %>
          <%= form.text_field :name, class: "form-control", placeholder: "Enter team name", required: true %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :description, 'Description' %>
          <%= form.text_area :description, class: "form-control", placeholder: "Describe the team (optional)" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :user_emails, "Add User Emails (separated by commas)" %>
          <%= form.text_area :user_emails, class: "form-control", rows: 3, placeholder: "e.g., user1@example.com, user2@example.com" %>
        </div>

        <div class="actions">
          <%= form.submit 'Save', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Back to Teams', work_teams_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/work_teams/show.html.erb
<div class="container mt-4">
  <h1 class="text-center">Info de <%= @team.name %></h1>

  <section class="mt-5">
    <h2>Boards:</h2>
    <div class="list-group">
      <% @boards.each do |board| %>
        <div class="list-group-item d-flex justify-content-between align-items-center">
          <%= board.name %>
          <%= link_to 'View', board_path(board), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    <%= link_to 'Add Board', new_work_team_board_path(@team), class: 'btn btn-success mt-3' %>
  </section>

  <section class="mt-5">
    <h2>Users:</h2>
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= "#{user.first_name} #{user.last_name}" %>
          <%= link_to 'View', user_path(user), class: 'btn btn-primary' %>
        </li>
      <% end %>
    </ul>
    <%= link_to 'Add User', add_users_work_team_path(@team), class: 'btn btn-success mt-3' %>
  </section>

</div>